# german titles ...',
# src:',
#https://www.leanoffice.at/der-titel-dschungel/',
#pdf: Bildungsministerium/ENIC NARIC Austria: österreichische akademische Grade öffentliche Universitäten 1.4.2020',
# order of items is important!! (e.g. 'Dr. med.univ.' should match before 'Dr.')
validTitles = [
    'Abg.z.NR',
    'ADir.',
    'AR',
    'Bakk. techn.',
    'BBA',
    'Bea.',
    'BEd',
    'B.Eng.',
    'Bgm.',
    'Bmstr.',
    'B.phil',
    'BSc',
    'Dres.',
    'DDr.',
    'Dr. h.c.',
    'Dr. iur.',
    'Dr. med.univ.',
    'Dr. med.vet.',
    'Dr. mont.',
    'Dr. phil.',
    'Dr. rer.nat.techn.',
    'Dr. rer.pol.',
    'Dr. rer.soc.oec.',
    'Dr. techn.',
    'Dipl.-Chem.',
    'Dipl.-Gwl',
    'Dipl.-Hdl.',
    'Dipl.-HLFL-Ing.',
    'Dipl.Holzw.',    
    'DDipl.-Ing.',
    'Dipl.-Ing. (FH)',
    'Dipl.-Ing.',
    'Dipl.Ing.',
    'Dipl.-Päd.',
    'diplômé',
    'Dir.',
    'EMHRD',
    'Gem. R.',
    'GR',
    'Hon.Prof.',
    'HR',
    'Ing.',
    'KommR',
    'LL.B.'
    'LLB',
    'LL.M.'
    'LLM',
    'Mag. (FH)',
    'Mag. arch.',
    'Mag. pharm.',
    'Mag. phil.',
    'Mag. rer.nat.',
    'Mag. rer.soc.oec.',
    'M.A.I.S.',
    'MBA',
    'MedR',
    'MIB',
    'MSc',
    'MES',
    'Parl. R',
    'Prof.',
    'StSekr.',
    'Univ.-Ass., Univ.Ass',
    'Univ.-Doz., Univ.Doz.',
    'Univ.-Lekt., Univ.Lekt.',
    'Univ.-Prof., Univ.Prof.',
    'B.phil.',
    'LLB. oec.',
    'BArch',
    'B.A.',
    'LL.B.',
    'B.Rel.Ed.',
    'B.Sc.',
    'BSSc',
    'BTh',
    'Bakk. art.',
    'Mag. art.',
    'M.phil.',
    'LLM. oec.',
    'LL.M. (Wirtschaftsrecht)',
    'M.A.',
    'MArch',
    'MEd',
    'MIBI',
    'LL.M.',
    'MLBT',
    'M.Rel.Ed.',
    'M.Sc.',
    'MScEF',
    'MScMF',
    'MSSc',
    'MTh',
    'Mag. med. vet.',
    'Dr. med. univ.',
    'Dr. med. dent.',
    'Dr.',
    'Mag. rer. nat.',
    'Mag. des. ind.',
    'Mag. phil. fac. theol.',
    'Mag. iur.',
    'Mag. rer. soc. oec.',
    'Mag. theol.',
    'Dr. med. vet. et scient.',
    'PhD',
    'Dr. scient. vet.',
    'Dr. nat. techn.',
    'Dr. med. univ. et scient. med.',
    'Dr. artium',
    'Dr. scient. med.',
    'Dr. rer. nat.',
    'Dr. rer. cur.',
    'Dr. phil. fac. theol.',
    'Dr. rer. soc. oec.',
    'Dr. theol.',
    'Dr. med. vet.',
    'Dr. rer. oec.',
    'Dr. med. dent. et scient. med.',
    'B. rer. nat.',
    'BStat',
    'B.techn.',
    'BAEd',
    'B.A.(Econ.)',
    'B.CDS',
    'B.Ed.Univ.',
    'BScMed',
    'BScN',
    'Bakk.',
    'Bakk. Komm.',
    'Bakk. rer. nat.',
    'Bakk. phil.',
    'Bakk. iur.',
    'Bakk. Soz.',
    'Bakk. Sport.',
    'BA',
    'Dipl.-Dolm.',
    'Dipl.-Kfm.',
    'Dipl.-Kffr. (FH)',
    'Dipl.-Kffr.',
    'Dipl.Vw.',
    'Dipl.-Vw.',
    'Dipl. Dolm.',
    'DI',
    'Dkffr.',
    'Dkfm.',
    'Dr. rer. comm.',
    'Dr. med. univ. et med. dent.',
    'Dr. pharm.',
    'Dr. rer. pol.',
    'Mag. Komm.',
    'Mr. pharm.',
    'Mag. Psych.',
    'Mag. Soz.',
    'Mag. Sport.',
    'Mag. iur. rer. oec.',
    'Maga.',
    'MMMag.',
    'MMag.',
    'Mag.',
    'MA. rer. nat.',
    'MA',
    'MStat',
    'M.A.(Econ.)',
    'MDes',
    'M.Ed.Univ.',
    'MScPH',
    'Tzt.'
]
