/**
 * WebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import NationalCouncilMeetingsPerYearDto from '../model/NationalCouncilMeetingsPerYearDto';

/**
* NationalCouncilMeeting service.
* @module api/NationalCouncilMeetingApi
* @version 1.0
*/
export default class NationalCouncilMeetingApi {

    /**
    * Constructs a new NationalCouncilMeetingApi. 
    * @alias module:api/NationalCouncilMeetingApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {Object} opts Optional parameters
     * @param {Number} [year] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/NationalCouncilMeetingsPerYearDto>} and HTTP response
     */
    apiNationalCouncilMeetingGetNationalCouncilMeetingsGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'year': opts['year']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [NationalCouncilMeetingsPerYearDto];
      return this.apiClient.callApi(
        '/api/NationalCouncilMeeting/getNationalCouncilMeetings', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.year 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/NationalCouncilMeetingsPerYearDto>}
     */
    apiNationalCouncilMeetingGetNationalCouncilMeetingsGet(opts) {
      return this.apiNationalCouncilMeetingGetNationalCouncilMeetingsGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
