/*
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.40
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SpeechesMetaData model module.
 * @module model/SpeechesMetaData
 * @version 1.0
 */
export class SpeechesMetaData {
  /**
   * Constructs a new <code>SpeechesMetaData</code>.
   * @alias module:model/SpeechesMetaData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SpeechesMetaData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SpeechesMetaData} obj Optional instance to populate.
   * @return {module:model/SpeechesMetaData} The populated <code>SpeechesMetaData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SpeechesMetaData();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('nameOfSpeaker'))
        obj.nameOfSpeaker = ApiClient.convertToType(data['nameOfSpeaker'], 'String');
      if (data.hasOwnProperty('nrOfSpeechInDebate'))
        obj.nrOfSpeechInDebate = ApiClient.convertToType(data['nrOfSpeechInDebate'], 'Number');
      if (data.hasOwnProperty('nrOfSpeechByThisPerson'))
        obj.nrOfSpeechByThisPerson = ApiClient.convertToType(data['nrOfSpeechByThisPerson'], 'Number');
      if (data.hasOwnProperty('typeOfSpeech'))
        obj.typeOfSpeech = ApiClient.convertToType(data['typeOfSpeech'], 'String');
      if (data.hasOwnProperty('startDateTime'))
        obj.startDateTime = ApiClient.convertToType(data['startDateTime'], 'Date');
      if (data.hasOwnProperty('timeLimitInSec'))
        obj.timeLimitInSec = ApiClient.convertToType(data['timeLimitInSec'], 'Boolean');
      if (data.hasOwnProperty('isVoluntaryTimeLimit'))
        obj.isVoluntaryTimeLimit = ApiClient.convertToType(data['isVoluntaryTimeLimit'], 'Boolean');
      if (data.hasOwnProperty('lengthOfSpeechInSec'))
        obj.lengthOfSpeechInSec = ApiClient.convertToType(data['lengthOfSpeechInSec'], 'Number');
      if (data.hasOwnProperty('nationalCouncilMeetingTitle'))
        obj.nationalCouncilMeetingTitle = ApiClient.convertToType(data['nationalCouncilMeetingTitle'], 'String');
      if (data.hasOwnProperty('topic'))
        obj.topic = ApiClient.convertToType(data['topic'], 'String');
      if (data.hasOwnProperty('hasSpeechFinished'))
        obj.hasSpeechFinished = ApiClient.convertToType(data['hasSpeechFinished'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
SpeechesMetaData.prototype.id = undefined;

/**
 * @member {String} nameOfSpeaker
 */
SpeechesMetaData.prototype.nameOfSpeaker = undefined;

/**
 * @member {Number} nrOfSpeechInDebate
 */
SpeechesMetaData.prototype.nrOfSpeechInDebate = undefined;

/**
 * @member {Number} nrOfSpeechByThisPerson
 */
SpeechesMetaData.prototype.nrOfSpeechByThisPerson = undefined;

/**
 * @member {String} typeOfSpeech
 */
SpeechesMetaData.prototype.typeOfSpeech = undefined;

/**
 * @member {Date} startDateTime
 */
SpeechesMetaData.prototype.startDateTime = undefined;

/**
 * @member {Boolean} timeLimitInSec
 */
SpeechesMetaData.prototype.timeLimitInSec = undefined;

/**
 * @member {Boolean} isVoluntaryTimeLimit
 */
SpeechesMetaData.prototype.isVoluntaryTimeLimit = undefined;

/**
 * @member {Number} lengthOfSpeechInSec
 */
SpeechesMetaData.prototype.lengthOfSpeechInSec = undefined;

/**
 * @member {String} nationalCouncilMeetingTitle
 */
SpeechesMetaData.prototype.nationalCouncilMeetingTitle = undefined;

/**
 * @member {String} topic
 */
SpeechesMetaData.prototype.topic = undefined;

/**
 * @member {Boolean} hasSpeechFinished
 */
SpeechesMetaData.prototype.hasSpeechFinished = undefined;

