/**
 * WebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SpeechesMetaData model module.
 * @module model/SpeechesMetaData
 * @version 1.0
 */
class SpeechesMetaData {
    /**
     * Constructs a new <code>SpeechesMetaData</code>.
     * @alias module:model/SpeechesMetaData
     */
    constructor() { 
        
        SpeechesMetaData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SpeechesMetaData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SpeechesMetaData} obj Optional instance to populate.
     * @return {module:model/SpeechesMetaData} The populated <code>SpeechesMetaData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SpeechesMetaData();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('nameOfSpeaker')) {
                obj['nameOfSpeaker'] = ApiClient.convertToType(data['nameOfSpeaker'], 'String');
            }
            if (data.hasOwnProperty('nrOfSpeechInDebate')) {
                obj['nrOfSpeechInDebate'] = ApiClient.convertToType(data['nrOfSpeechInDebate'], 'Number');
            }
            if (data.hasOwnProperty('nrOfSpeechByThisPerson')) {
                obj['nrOfSpeechByThisPerson'] = ApiClient.convertToType(data['nrOfSpeechByThisPerson'], 'Number');
            }
            if (data.hasOwnProperty('typeOfSpeech')) {
                obj['typeOfSpeech'] = ApiClient.convertToType(data['typeOfSpeech'], 'String');
            }
            if (data.hasOwnProperty('startDateTime')) {
                obj['startDateTime'] = ApiClient.convertToType(data['startDateTime'], 'Date');
            }
            if (data.hasOwnProperty('timeLimitInSec')) {
                obj['timeLimitInSec'] = ApiClient.convertToType(data['timeLimitInSec'], 'Boolean');
            }
            if (data.hasOwnProperty('isVoluntaryTimeLimit')) {
                obj['isVoluntaryTimeLimit'] = ApiClient.convertToType(data['isVoluntaryTimeLimit'], 'Boolean');
            }
            if (data.hasOwnProperty('lengthOfSpeechInSec')) {
                obj['lengthOfSpeechInSec'] = ApiClient.convertToType(data['lengthOfSpeechInSec'], 'Number');
            }
            if (data.hasOwnProperty('nationalCouncilMeetingTitle')) {
                obj['nationalCouncilMeetingTitle'] = ApiClient.convertToType(data['nationalCouncilMeetingTitle'], 'String');
            }
            if (data.hasOwnProperty('topic')) {
                obj['topic'] = ApiClient.convertToType(data['topic'], 'String');
            }
            if (data.hasOwnProperty('hasSpeechFinished')) {
                obj['hasSpeechFinished'] = ApiClient.convertToType(data['hasSpeechFinished'], 'Boolean');
            }
            if (data.hasOwnProperty('politicalPartie')) {
                obj['politicalPartie'] = ApiClient.convertToType(data['politicalPartie'], 'String');
            }
            if (data.hasOwnProperty('topNr')) {
                obj['topNr'] = ApiClient.convertToType(data['topNr'], 'String');
            }
            if (data.hasOwnProperty('meetingNr')) {
                obj['meetingNr'] = ApiClient.convertToType(data['meetingNr'], 'Number');
            }
            if (data.hasOwnProperty('legislature')) {
                obj['legislature'] = ApiClient.convertToType(data['legislature'], 'String');
            }
            if (data.hasOwnProperty('textMatchScore')) {
                obj['textMatchScore'] = ApiClient.convertToType(data['textMatchScore'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SpeechesMetaData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SpeechesMetaData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['nameOfSpeaker'] && !(typeof data['nameOfSpeaker'] === 'string' || data['nameOfSpeaker'] instanceof String)) {
            throw new Error("Expected the field `nameOfSpeaker` to be a primitive type in the JSON string but got " + data['nameOfSpeaker']);
        }
        // ensure the json data is a string
        if (data['typeOfSpeech'] && !(typeof data['typeOfSpeech'] === 'string' || data['typeOfSpeech'] instanceof String)) {
            throw new Error("Expected the field `typeOfSpeech` to be a primitive type in the JSON string but got " + data['typeOfSpeech']);
        }
        // ensure the json data is a string
        if (data['nationalCouncilMeetingTitle'] && !(typeof data['nationalCouncilMeetingTitle'] === 'string' || data['nationalCouncilMeetingTitle'] instanceof String)) {
            throw new Error("Expected the field `nationalCouncilMeetingTitle` to be a primitive type in the JSON string but got " + data['nationalCouncilMeetingTitle']);
        }
        // ensure the json data is a string
        if (data['topic'] && !(typeof data['topic'] === 'string' || data['topic'] instanceof String)) {
            throw new Error("Expected the field `topic` to be a primitive type in the JSON string but got " + data['topic']);
        }
        // ensure the json data is a string
        if (data['politicalPartie'] && !(typeof data['politicalPartie'] === 'string' || data['politicalPartie'] instanceof String)) {
            throw new Error("Expected the field `politicalPartie` to be a primitive type in the JSON string but got " + data['politicalPartie']);
        }
        // ensure the json data is a string
        if (data['topNr'] && !(typeof data['topNr'] === 'string' || data['topNr'] instanceof String)) {
            throw new Error("Expected the field `topNr` to be a primitive type in the JSON string but got " + data['topNr']);
        }
        // ensure the json data is a string
        if (data['legislature'] && !(typeof data['legislature'] === 'string' || data['legislature'] instanceof String)) {
            throw new Error("Expected the field `legislature` to be a primitive type in the JSON string but got " + data['legislature']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
SpeechesMetaData.prototype['id'] = undefined;

/**
 * @member {String} nameOfSpeaker
 */
SpeechesMetaData.prototype['nameOfSpeaker'] = undefined;

/**
 * @member {Number} nrOfSpeechInDebate
 */
SpeechesMetaData.prototype['nrOfSpeechInDebate'] = undefined;

/**
 * @member {Number} nrOfSpeechByThisPerson
 */
SpeechesMetaData.prototype['nrOfSpeechByThisPerson'] = undefined;

/**
 * @member {String} typeOfSpeech
 */
SpeechesMetaData.prototype['typeOfSpeech'] = undefined;

/**
 * @member {Date} startDateTime
 */
SpeechesMetaData.prototype['startDateTime'] = undefined;

/**
 * @member {Boolean} timeLimitInSec
 */
SpeechesMetaData.prototype['timeLimitInSec'] = undefined;

/**
 * @member {Boolean} isVoluntaryTimeLimit
 */
SpeechesMetaData.prototype['isVoluntaryTimeLimit'] = undefined;

/**
 * @member {Number} lengthOfSpeechInSec
 */
SpeechesMetaData.prototype['lengthOfSpeechInSec'] = undefined;

/**
 * @member {String} nationalCouncilMeetingTitle
 */
SpeechesMetaData.prototype['nationalCouncilMeetingTitle'] = undefined;

/**
 * @member {String} topic
 */
SpeechesMetaData.prototype['topic'] = undefined;

/**
 * @member {Boolean} hasSpeechFinished
 */
SpeechesMetaData.prototype['hasSpeechFinished'] = undefined;

/**
 * @member {String} politicalPartie
 */
SpeechesMetaData.prototype['politicalPartie'] = undefined;

/**
 * @member {String} topNr
 */
SpeechesMetaData.prototype['topNr'] = undefined;

/**
 * @member {Number} meetingNr
 */
SpeechesMetaData.prototype['meetingNr'] = undefined;

/**
 * @member {String} legislature
 */
SpeechesMetaData.prototype['legislature'] = undefined;

/**
 * @member {Number} textMatchScore
 */
SpeechesMetaData.prototype['textMatchScore'] = undefined;






export default SpeechesMetaData;

