/*
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TopicSearchResultDto model module.
 * @module model/TopicSearchResultDto
 * @version 1.0
 */
export class TopicSearchResultDto {
  /**
   * Constructs a new <code>TopicSearchResultDto</code>.
   * @alias module:model/TopicSearchResultDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TopicSearchResultDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TopicSearchResultDto} obj Optional instance to populate.
   * @return {module:model/TopicSearchResultDto} The populated <code>TopicSearchResultDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TopicSearchResultDto();
      if (data.hasOwnProperty('topic'))
        obj.topic = ApiClient.convertToType(data['topic'], 'String');
      if (data.hasOwnProperty('topNr'))
        obj.topNr = ApiClient.convertToType(data['topNr'], 'String');
      if (data.hasOwnProperty('meetingNr'))
        obj.meetingNr = ApiClient.convertToType(data['meetingNr'], 'Number');
      if (data.hasOwnProperty('legislature'))
        obj.legislature = ApiClient.convertToType(data['legislature'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} topic
 */
TopicSearchResultDto.prototype.topic = undefined;

/**
 * @member {String} topNr
 */
TopicSearchResultDto.prototype.topNr = undefined;

/**
 * @member {Number} meetingNr
 */
TopicSearchResultDto.prototype.meetingNr = undefined;

/**
 * @member {String} legislature
 */
TopicSearchResultDto.prototype.legislature = undefined;

