/**
 * WebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TypeOfSpeechCountDto model module.
 * @module model/TypeOfSpeechCountDto
 * @version 1.0
 */
class TypeOfSpeechCountDto {
    /**
     * Constructs a new <code>TypeOfSpeechCountDto</code>.
     * @alias module:model/TypeOfSpeechCountDto
     */
    constructor() { 
        
        TypeOfSpeechCountDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TypeOfSpeechCountDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TypeOfSpeechCountDto} obj Optional instance to populate.
     * @return {module:model/TypeOfSpeechCountDto} The populated <code>TypeOfSpeechCountDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TypeOfSpeechCountDto();

            if (data.hasOwnProperty('typeOfSpeech')) {
                obj['typeOfSpeech'] = ApiClient.convertToType(data['typeOfSpeech'], 'String');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TypeOfSpeechCountDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TypeOfSpeechCountDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['typeOfSpeech'] && !(typeof data['typeOfSpeech'] === 'string' || data['typeOfSpeech'] instanceof String)) {
            throw new Error("Expected the field `typeOfSpeech` to be a primitive type in the JSON string but got " + data['typeOfSpeech']);
        }

        return true;
    }


}



/**
 * @member {String} typeOfSpeech
 */
TypeOfSpeechCountDto.prototype['typeOfSpeech'] = undefined;

/**
 * @member {Number} count
 */
TypeOfSpeechCountDto.prototype['count'] = undefined;






export default TypeOfSpeechCountDto;

