/*
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TypeOfSpeechCountDto model module.
 * @module model/TypeOfSpeechCountDto
 * @version 1.0
 */
export class TypeOfSpeechCountDto {
  /**
   * Constructs a new <code>TypeOfSpeechCountDto</code>.
   * @alias module:model/TypeOfSpeechCountDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TypeOfSpeechCountDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TypeOfSpeechCountDto} obj Optional instance to populate.
   * @return {module:model/TypeOfSpeechCountDto} The populated <code>TypeOfSpeechCountDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TypeOfSpeechCountDto();
      if (data.hasOwnProperty('typeOfSpeech'))
        obj.typeOfSpeech = ApiClient.convertToType(data['typeOfSpeech'], 'String');
      if (data.hasOwnProperty('count'))
        obj.count = ApiClient.convertToType(data['count'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} typeOfSpeech
 */
TypeOfSpeechCountDto.prototype.typeOfSpeech = undefined;

/**
 * @member {Number} count
 */
TypeOfSpeechCountDto.prototype.count = undefined;

