/*
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WebApi);
  }
}(this, function(expect, WebApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LegislatureMeetingsListDto', function() {
      beforeEach(function() {
        instance = new WebApi.LegislatureMeetingsListDto();
      });

      it('should create an instance of LegislatureMeetingsListDto', function() {
        // TODO: update the code to test LegislatureMeetingsListDto
        expect(instance).to.be.a(WebApi.LegislatureMeetingsListDto);
      });

      it('should have the property legislature (base name: "legislature")', function() {
        // TODO: update the code to test the property legislature
        expect(instance).to.have.property('legislature');
        // expect(instance.legislature).to.be(expectedValueLiteral);
      });

      it('should have the property meetings (base name: "meetings")', function() {
        // TODO: update the code to test the property meetings
        expect(instance).to.have.property('meetings');
        // expect(instance.meetings).to.be(expectedValueLiteral);
      });

    });
  });

}));
