class State:
    Start = "initialize"
    DetermineWordMeaning = "determineWordMeaning"    
    ConnectingWord = "ConnectingWord"
    Activity = "activity"
    EntityPoliticalParty = "entity_PoliticalParty"
    EntityPersonOrPeople = "entity_PersonOrPeople"
    BehaviourDescription = "behaviourDescription"
    Speech = "interjection"
    NewItem = "newItem"     
    Ending = "ending"  