class State:
    Start = "Start"
    Activity = "DetectActivity"
    ActivityConnectingWord = "ActivityConnectingWord"
    BeginningOfEntity = "BeginningOfEntity"
    EntityPoliticalParty = "DetectEntityName"
    EntityPersonOrPeople = "EntityPersonOrPeople"
    EntityPoliticalPartyConnectingWord = "EntityPoliticalPartyConnectingWord"
    EntityPersonOrPeopleConnectingWord = "EntityPersonOrPeopleConnectingWord"
    BehaviourDescription = "BehaviourDescription"
    Speech = "Speech"
    ImplicitActivity = "DetectActivityImplicit"
    NewItem = "NewItem"     
    Ending = "Ending"  