class State:
    Start = "Start"
    DetermineWordMeaning = "DetermineWordMeaning"    
    ConnectingWord = "ConnectingWord"
    Activity = "DetectActivity"
    EntityPoliticalParty = "DetectEntityName"
    EntityPersonOrPeople = "EntityPersonOrPeople"
    BehaviourDescription = "BehaviourDescription"
    Speech = "Speech"
    NewItem = "NewItem"     
    Ending = "Ending"  