name: DataScraper Azure Container Registry

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'dataScraper/**'
    - '.github/workflows/aut-parliamentary-data-scraping-AutoDeployTrigger-0ba95881-7efa-44d8-9919-0b393e06b5ad.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: autparlamentarydatascraping.azurecr.io
          username: ${{ secrets.AUTPARLIAMENTARYDATASCRAPING_REGISTRY_USERNAME }}
          password: ${{ secrets.AUTPARLIAMENTARYDATASCRAPING_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: autparlamentarydatascraping.azurecr.io/aut-parliamentary-data-scraping:${{ github.sha }}
          file: ./dataScraper/Dockerfile
          context: ./dataScraper/
          
