# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Backend Azure App Service

on:
  push:
    paths:
    - 'Backend/**'
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy-env:
        description: 'Select environment'
        required: true
        default: 'int'
        type: choice
        options:
        - int
        - prod

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./Backend
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build Backend.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish  Backend.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy-int:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'int'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'aut-parl-api(int)'
          slot-name: 'int'
          publish-profile:  ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AF57F820C01B4BFF971FB02D8AEB0F67 }}
          package: .
  
  deploy-prod:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'prod'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'aut-parl-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AF57F820C01B4BFF971FB02D8AEB0F67 }}
          package: .

